server:
  port: 8080

spring:
  application:
    name: saga-demo

chain:
  xml:
    path: classpath:spring/handler-stack-integ.xml

okhttp:
  connectTimeout: 3
  readTimeout: 5
  keepAliveDuration: 5
  maxIdleConnections: 10
